apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: Symfony-API-Template
  title: Symfony API Template
  description: Thats a template to create a Symfony API
spec:
  owner: development
  type: service

  parameters:
    - title: Fill in some steps
      required:
        - component_id
        - environment
      properties:
        component_id:
          title: Component ID
          type: string
          description: Component name
          pattern: '^([a-zA-Z0-9]+(-[a-zA-Z0-9]+)*)$'
        environment:
          title: Environment
          type: string
          description: Environment for the component
          enum:
            - dev
            - staging
            - prod
  steps:
    - id: fetch-base
      name: Fetch Base
      action: fetch:template
      input:
        url: ./template
        values:
          app_name: ${{parameters.component_id}}
          app_env: ${{parameters.environment}}

    - id: publish
      name: Publish
      action: publish:github
      input:
        description: This is ${{ parameters.component_id }}
        repoUrl: github.com?owner=nachoKDevOrg&repo=${{parameters.component_id}}
        protectDefaultBranch: false
        repoVisibility: public

    - id: register
      name: Register
      action: catalog:register
      input:
        repoContentsUrl: ${{ steps['publish'].output.repoContentsUrl }}
        catalogInfoPath: "/catalog-info.yaml"

  output:
    links:
      - title: Repository
        url: ${{ steps['publish'].output.remoteUrl }}
