FROM php:8.3-cli

# Dependencias del sistema
RUN apt-get update && apt-get install -y \
    git \
    unzip \
    libpq-dev \
    && docker-php-ext-install pdo pdo_pgsql \
    && rm -rf /var/lib/apt/lists/*

# Composer
COPY --from=composer:2 /usr/bin/composer /usr/bin/composer

# App
WORKDIR /src
COPY ./src /src

# Servidor HTTP embebido (DEV)
CMD ["php", "-S", "0.0.0.0:8000", "-t", "public"]
